services:
  - type: web
    name: bfhl-api-sayansh
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: BFHL_USER_FULL_NAME
        value: sayansh_pal
      - key: BFHL_USER_DOB_DDMMYYYY
        value: "30102005"
      - key: BFHL_USER_EMAIL
        value: sayanshpal@gmail.com
      - key: BFHL_USER_ROLL_NUMBER
        value: 0827CI231121
